/* LOGO */
export const GET_ALL_NUMBER_SIZES = 'GET_ALL_NUMBER_SIZES'
export const GET_ALL_TEXT_SIZES = 'GET_ALL_TEXT_SIZES'
export const GET_ALL_LOGOS = 'GET_ALL_LOGOS'
export const GET_ALL_LOGO_SIZES = 'GET_ALL_LOGO_SIZES'
export const GET_ALL_LOGO_TYPES = 'GET_ALL_LOGO_TYPES'

/* COLOR */
export const MASS_UPDAT_PRICES_OF_SIZES = 'MASS_UPDAT_PRICES_OF_SIZES'
export const GET_SIZES = 'GET_SIZES'
export const GET_ALL_SIZES = 'GET_ALL_SIZES'
export const GET_ALL_COLORS = 'GET_ALL_COLORS'

/* CANAVAS */
export const SHOW_DELETE_BTN = 'SHOW_DELETE_BTN'

/* MODEL */
export const GET_ALL_MODELS = 'GET_ALL_MODELS'

/* TYPE */
export const GET_ALL_TYPES = 'GET_ALL_TYPES'

/* NEWS */
export const GET_ALL_NEWS = 'GET_ALL_NEWS'

/* DISCOUNT */
export const GET_ALL_DISCOUNTS = 'GET_ALL_DISCOUNTS'

/* Dialog element */
export const SET_RESULT_COPY_DIALOG = 'SET_RESULT_COPY_DIALOG'
export const SET_RESULT_CONFIRM_DIALOG = 'SET_RESULT_CONFIRM_DIALOG'
export const SHOW_CONGRATULATION_DIALOG = 'SHOW_CONGRATULATION_DIALOG'
export const CLEAR_MESSAGE_DIALOG = 'CLEAR_MESSAGE_DIALOG'
export const SET_MESSAGE_DIALOG = 'SET_MESSAGE_DIALOG'

/* Busy element */
export const SET_LOADING = 'SET_LOADING'

/* Auth */
export const SET_ADMIN_ROLE = 'SET_ADMIN_ROLE'
export const RESET_PAGE_OF_USERS = 'RESET_PAGE_OF_USERS'
export const INCREASE_PAGE_OF_USERS = 'INCREASE_PAGE_OF_USERS'
export const RECIEVE_NEXT_PART_OF_USERS = 'RECIEVE_NEXT_PART_OF_USERS'
export const RECIEVE_ALL_USERS = 'RECIEVE_ALL_USERS'
export const RECIEVE_USER_SETTINGS = 'RECIEVE_USER_SETTINGS'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_ERRORS = 'SET_ERRORS'
export const SET_USER = 'SET_USER'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_NAME = 'SET_NAME'
export const SET_ROLE = 'SET_ROLE'
