/* TYPE */
export const GET_ALL_TYPES = 'GET_ALL_TYPES'

/* Dialog element */
export const SET_RESULT_CONFIRM_DIALOG = 'SET_RESULT_CONFIRM_DIALOG'
export const SHOW_CONGRATULATION_DIALOG = 'SHOW_CONGRATULATION_DIALOG'
export const CLEAR_MESSAGE_DIALOG = 'CLEAR_MESSAGE_DIALOG'
export const SET_MESSAGE_DIALOG = 'SET_MESSAGE_DIALOG'

/* Busy element */
export const SET_LOADING = 'SET_LOADING'
